# Generated by Django 6.0.1 on 2026-02-26 00:09

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del usuario', max_length=254, unique=True)),
                ('first_name', models.CharField(help_text='Nombre del usuario', max_length=150)),
                ('last_name', models.CharField(help_text='Apellido del usuario', max_length=150)),
                ('telefono', models.CharField(help_text='El teléfono es obligatorio y debe tener un formato ecuatoriano válido.', max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe empezar con '09' y tener 10 dígitos en total (ej: 0991234567).", regex='^09\\d{8}$')])),
                ('casa_departamento', models.CharField(blank=True, help_text='Número o identificador de la casa/departamento (ej: Casa 15, Dpto 3B)', max_length=50, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vecino', 'Vecino')], default='vecino', help_text='Rol del usuario en el sistema', max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='usuarios/fotos_perfil/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el conjunto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['casa_departamento', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del evento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento', null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del evento')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin del evento')),
                ('categoria', models.CharField(choices=[('minga', 'Minga'), ('reunion', 'Reunión'), ('mantenimiento', 'Mantenimiento'), ('evento_social', 'Evento Social'), ('otro', 'Otro')], default='otro', help_text='Categoría del evento', max_length=20)),
                ('color', models.CharField(default='#667eea', help_text='Color del evento en formato hexadecimal', max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del evento')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Última actualización del evento')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(help_text='Número de casa o departamento donde reside la mascota', max_length=14)),
                ('nombre', models.CharField(help_text='Nombre de la mascota', max_length=100)),
                ('dueno', models.CharField(help_text='Nombre del dueño de la mascota', max_length=200)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pajaro', 'Pájaro'), ('conejo', 'Conejo'), ('hamster', 'Hámster'), ('otro', 'Otro')], default='otro', help_text='Tipo de mascota', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la mascota (color, características, etc)', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la mascota')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro de la mascota está activo')),
                ('foto', models.ImageField(blank=True, help_text='Foto de la mascota', null=True, upload_to='mascotas/fotos/')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario de la mascota', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['numero_casa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió el mensaje')),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto y descriptivo', max_length=200)),
                ('contenido', models.TextField(help_text='Cuerpo del mensaje o noticia')),
                ('tipo', models.CharField(choices=[('comunicado', '📢 Comunicado'), ('novedad', '✨ Novedad'), ('finanzas', '💰 Finanzas'), ('mantenimiento', '🛠️ Mantenimiento')], default='comunicado', help_text='Categoría de la publicación', max_length=20)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen ilustrativa opcional', null=True, upload_to='publicaciones/imagenes/')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Documento adjunto (ej. Estado de Cuenta)', null=True, upload_to='publicaciones/documentos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se hizo pública la nota')),
                ('autor', models.ForeignKey(help_text='Administrador que crea la publicación', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('permiso', 'Permiso'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], default='otro', help_text='Tipo de solicitud', max_length=20)),
                ('titulo', models.CharField(help_text='Asunto de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la solicitud', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización de la solicitud')),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(help_text='Número de casa o departamento (ej: Casa 15, Depto 3B)', max_length=14)),
                ('dueno', models.CharField(help_text='Nombre del propietario del vehículo', max_length=150)),
                ('placa', models.CharField(help_text='Placa del vehículo (ej: ABC-1234)', max_length=20, unique=True)),
                ('marca', models.CharField(help_text='Marca del vehículo (ej: Toyota, Honda)', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo del vehículo (ej: Corolla, Civic)', max_length=100)),
                ('color', models.CharField(help_text='Color del vehículo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del vehículo')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ReaccionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de la reacción')),
                ('usuario', models.ForeignKey(help_text='Usuario que reacciona', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_solicitud', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que se reacciona', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='usuarios.solicitud')),
            ],
            options={
                'verbose_name': 'Reacción de Solicitud',
                'verbose_name_plural': 'Reacciones de Solicitud',
                'db_table': 'reacciones_solicitud',
                'unique_together': {('usuario', 'solicitud')},
            },
        ),
    ]
