# Generated by Django 6.0.1 on 2026-01-11 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del evento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento', null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del evento')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin del evento')),
                ('color', models.CharField(default='#667eea', help_text='Color del evento en formato hexadecimal', max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del evento')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Última actualización del evento')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
