# Generated by Django 6.0.1 on 2026-01-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=10, null=True),
        ),
    ]
