# Generated by Django 4.2 on 2026-01-11 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de casa o departamento (ej: 1, 2A, 15B)', max_length=10, unique=True)),
                ('disponible', models.BooleanField(default=True, help_text='Indica si la casa está disponible para asignar')),
                ('creada_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Casa/Departamento',
                'verbose_name_plural': 'Casas/Departamentos',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(help_text='Nombre del usuario', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(help_text='Apellido del usuario', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='casa_departamento',
            field=models.ForeignKey(blank=True, help_text='Casa o departamento asignado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residente', to='usuarios.casa', unique=True),
        ),
    ]
