# Generated by Django 4.2 on 2026-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_casa_alter_usuario_email_alter_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='casa_departamento',
            field=models.CharField(default='', help_text='Número de casa o departamento (ej: Casa 15, Depto 3B)', max_length=14),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
