# Generated by Django 6.0.1 on 2026-01-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_casa_departamento_delete_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('minga', 'Minga'), ('reunion', 'Reunión'), ('mantenimiento', 'Mantenimiento'), ('evento_social', 'Evento Social'), ('otro', 'Otro')], default='otro', help_text='Categoría del evento', max_length=20),
        ),
    ]
