# Generated by Django 6.0.1 on 2026-01-11 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_casa_departamento_delete_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('permiso', 'Permiso'), ('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], default='otro', help_text='Tipo de solicitud', max_length=20)),
                ('titulo', models.CharField(help_text='Asunto de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la solicitud', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización de la solicitud')),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
