# Generated by Django 6.0.1 on 2026-01-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_evento_categoria'),
        ('usuarios', '0006_solicitud'),
    ]

    operations = [
    ]
