# Generated by Django 6.0.1 on 2026-01-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_0006_evento_categoria_0006_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(help_text='Número de casa o departamento donde reside la mascota', max_length=14)),
                ('nombre', models.CharField(help_text='Nombre de la mascota', max_length=100)),
                ('dueno', models.CharField(help_text='Nombre del dueño de la mascota', max_length=200)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pajaro', 'Pájaro'), ('conejo', 'Conejo'), ('hamster', 'Hámster'), ('otro', 'Otro')], default='otro', help_text='Tipo de mascota', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la mascota (color, características, etc)', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la mascota')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro de la mascota está activo')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['numero_casa', 'nombre'],
            },
        ),
    ]
