# Generated by Django 6.0.1 on 2026-01-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la mascota', null=True, upload_to='mascotas/fotos/'),
        ),
    ]
