# Generated by Django 6.0.1 on 2026-01-29 03:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mascota_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Ãšltima actualizaciÃ³n del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('minga', 'Minga'), ('reunion', 'ReuniÃ³n'), ('mantenimiento', 'Mantenimiento'), ('evento_social', 'Evento Social'), ('otro', 'Otro')], default='otro', help_text='CategorÃ\xada del evento', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n detallada del evento', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(help_text='TÃ\xadtulo del evento', max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro de la mascota estÃ¡ activo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n adicional de la mascota (color, caracterÃ\xadsticas, etc)', null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(help_text='Nombre del dueÃ±o de la mascota', max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='numero_casa',
            field=models.CharField(help_text='NÃºmero de casa o departamento donde reside la mascota', max_length=14),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pajaro', 'PÃ¡jaro'), ('conejo', 'Conejo'), ('hamster', 'HÃ¡mster'), ('otro', 'Otro')], default='otro', help_text='Tipo de mascota', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(help_text='DescripciÃ³n detallada de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Ãšltima actualizaciÃ³n de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n de la solicitud'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario estÃ¡ activo en el conjunto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='casa_departamento',
            field=models.CharField(help_text='NÃºmero de casa o departamento (ej: Casa 15, Depto 3B)', max_length=14),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrÃ³nico del usuario', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='NÃºmero de telÃ©fono del usuario', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El telÃ©fono solo puede contener nÃºmeros', regex='^\\d+$')]),
        ),
        # migrations.CreateModel(
        #     name='Mensaje',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('contenido', models.TextField(help_text='Contenido del mensaje')),
        #         ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leÃ\xaddo por el destinatario')),
        #         ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se enviÃ³ el mensaje')),
        #         ('destinatario', models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
        #         ('remitente', models.ForeignKey(help_text='Usuario que envÃ\xada el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'verbose_name': 'Mensaje',
        #         'verbose_name_plural': 'Mensajes',
        #         'ordering': ['fecha_envio'],
        #     },
        # ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto y descriptivo', max_length=200)),
                ('contenido', models.TextField(help_text='Cuerpo del mensaje o noticia')),
                ('tipo', models.CharField(choices=[('comunicado', '📢 Comunicado'), ('novedad', '✨ Novedad'), ('finanzas', '💰 Finanzas'), ('mantenimiento', '🛠️ Mantenimiento')], default='comunicado', help_text='Categoría de la publicación', max_length=20)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen ilustrativa opcional', null=True, upload_to='publicaciones/imagenes/')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Documento adjunto (ej. Estado de Cuenta)', null=True, upload_to='publicaciones/documentos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se hizo pública la nota')),
                ('autor', models.ForeignKey(help_text='Administrador que crea la publicación', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
