# Generated by Django 6.0.1 on 2026-01-28 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mascota_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió el mensaje')),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
