# Generated by Django 6.0.1 on 2026-01-28 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mascota_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió el mensaje')),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(help_text='Número de casa o departamento (ej: Casa 15, Depto 3B)', max_length=14)),
                ('dueno', models.CharField(help_text='Nombre del propietario del vehículo', max_length=150)),
                ('placa', models.CharField(help_text='Placa del vehículo (ej: ABC-1234)', max_length=20, unique=True)),
                ('marca', models.CharField(help_text='Marca del vehículo (ej: Toyota, Honda)', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo del vehículo (ej: Corolla, Civic)', max_length=100)),
                ('color', models.CharField(help_text='Color del vehículo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del vehículo')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
