# Generated by Django 6.0.1 on 2026-01-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_managers_alter_evento_actualizado_en_and_more'),
        ('usuarios', '0010_alter_usuario_managers_mascota_usuario_mensaje_and_more'),
    ]

    operations = [
    ]
