# Generated by Django 6.0.1 on 2026-02-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_mensaje'),
        ('usuarios', '0011_merge_20260130_1940'),
    ]

    operations = [
    ]
