# Generated by Django 6.0.1 on 2026-02-03 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_merge_20260130_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se enviÃ³ el mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leÃ\xaddo por el destinatario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(help_text='Usuario que envÃ\xada el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
