# Generated by Django 6.0.1 on 2026-02-24 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_mensaje_fecha_envio_alter_mensaje_leido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='casa_departamento',
            field=models.CharField(blank=True, help_text='Número o identificador de la casa/departamento (ej: Casa 15, Dpto 3B)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vecino', 'Vecino')], default='vecino', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0999999999', help_text='El teléfono es obligatorio y debe tener un formato ecuatoriano válido.', max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe empezar con '09' y tener 10 dígitos en total (ej: 0991234567).", regex='^09\\d{8}$')]),
            preserve_default=False,
        ),
    ]
