# Generated by Django 6.0.1 on 2026-02-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_casa_departamento_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('minga', 'Minga'), ('reunion', 'Reunión'), ('mantenimiento', 'Mantenimiento'), ('evento_social', 'Evento Social'), ('otro', 'Otro')], default='otro', help_text='Categoría del evento', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del evento', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(help_text='Título del evento', max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro de la mascota está activo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional de la mascota (color, características, etc)', null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueno',
            field=models.CharField(help_text='Nombre del dueño de la mascota', max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='numero_casa',
            field=models.CharField(help_text='Número de casa o departamento donde reside la mascota', max_length=14),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pajaro', 'Pájaro'), ('conejo', 'Conejo'), ('hamster', 'Hámster'), ('otro', 'Otro')], default='otro', help_text='Tipo de mascota', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió el mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización de la solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo en el conjunto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del usuario', max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='evento',
            table='eventos',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='mascotas',
        ),
        migrations.AlterModelTable(
            name='mensaje',
            table='mensajes',
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicaciones',
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitudes',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculos',
        ),
    ]
