# Generated by Django 6.0.1 on 2026-02-25 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_evento_actualizado_en_alter_evento_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de la reacción')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que se reacciona', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='usuarios.solicitud')),
                ('usuario', models.ForeignKey(help_text='Usuario que reacciona', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_solicitud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacción de Solicitud',
                'verbose_name_plural': 'Reacciones de Solicitud',
                'db_table': 'reacciones_solicitud',
                'unique_together': {('usuario', 'solicitud')},
            },
        ),
    ]
